package linea

import ads_std.*
import org.sikuli.script.Pattern
import org.sikuli.script.Screen

suspend fun hopPool(screen: Screen) {
    screen.wait(2.0)
    browserOpenUrl(screen, "chrome-extension://cknlgcbdfhknkoidcefkpmlplfndfmll/home.html")
    metamaskUnlock(screen)
    screen.wait(2.0)
    browserOpenUrl(screen, "https://goerli.hop.exchange/#/convert?token=ETH&sourceNetwork=linea")
    screen.wait("hop_click_to_wrap.png", 8.0)
    screen.wait(1.0)
    tryToClickQueue(screen, Pattern("hop_connect_wallet.png"))
    tryToClickQueue(screen, Pattern("hop_metamask.png"))
    screen.wait("hop_click_to_wrap.png", 8.0)
    browserScroll(screen, 3)
    screen.wait("hop_click_to_wrap.png")
    screen.queueTakeClickRelease()
    screen.wait(Pattern("hop_amount.png").targetOffset(360, 0))
    screen.queueTakeClick()
    screen.paste("0.1")
    screen.queueRelease()
    screen.wait("hop_wrap_button.png")
    screen.queueTakeClickRelease()
    screen.wait(2.0)
    metamaskApprove(screen)
    screen.wait(2.0)
    metamaskSwitchNetwork(screen)
    screen.wait("hop_big_wrap_button.png")
    screen.queueTakeClickRelease()
    screen.wait(3.0)
    metamaskConfirmUntilItDisappears(screen)
    screen.wait("hop_unwrap_button.png", 120.0)
    browserScroll(screen, 2)
    screen.wait("hop_max_button.png", 12.0)
    screen.queueTakeClickRelease()
    screen.wait("hop_approve_button.png")
    screen.queueTakeClickRelease()
    screen.wait(1.0)
    screen.wait("hop_approve_button.png")
    screen.queueTakeClickRelease()
    screen.wait("metamask_handler_icon_dark.png", 18.0)
    screen.wait(2.0)
    metamaskScrollDark(screen, 2, 220, 220)
    metamaskMax(screen)
    screen.wait(2.0)
    metamaskNext(screen)
    metamaskScrollDark(screen, 2, 220, 220)
    metamaskApprove(screen)
    screen.wait("hop_convert_button.png", 120.0)
    screen.wait(1.0)
    screen.wait("hop_convert_button.png")
    screen.queueTakeClickRelease()
    screen.wait(1.0)
    screen.wait("hop_convert_button.png")
    screen.queueTakeClickRelease()
    metamaskConfirmUntilItDisappears(screen, time = 8.0)
    screen.wait("hop_insufficient_funds.png", 120.0)
    browserOpenUrl(screen, "https://goerli.hop.exchange/#/pool/deposit?token=ETH&sourceNetwork=linea")
    screen.wait(3.0)
    browserScroll(screen, 4)
    screen.wait(2.0)
    browserScroll(screen, 3)
    screen.wait(5.0)
    screen.wait(Pattern("hop_heth.png").targetOffset(134, -50))
    screen.queueTakeClickRelease()
    screen.wait("hop_preview_button.png")
    screen.queueTakeClickRelease()
    screen.wait("hop_deposit_button.png")
    screen.queueTakeClickRelease()
    screen.wait("metamask_handler_icon_dark.png", 18.0)
    screen.wait(5.0)
    metamaskScrollDark(screen, 2, 220, 220)
    metamaskMax(screen)
    screen.wait(2.0)
    metamaskNext(screen)
    metamaskScrollDark(screen, 2, 220, 220)
    metamaskApprove(screen)
    screen.wait(3.0)
    metamaskConfirmUntilItDisappears(screen, time = 120.0)
    screen.wait("hop_done_button.png", 120.0)
}